# Don't print a new line at the start of the prompt
add_newline = false
# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$cmd_duration$directory $git_branch ó±¦™ $time
$character
"""

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ï…¸](bold fg:green) "
error_symbol = "[ó°œº](bold fg:red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: yellow"
symbol = "ó°˜¬"
truncation_length = 4
truncation_symbol = ""
format = "â€¢ [$symbol $branch(:$remote_branch)](fg:red)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤· â€"
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](red)'
renamed = " âœï¸ "
deleted = " ğŸ—‘ "

[hostname]
ssh_only = false
format = "[â€¢$hostname](bg:red bold fg:black)[î‚´](bold fg:red )"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed red"

[time]
disabled = false
format = '[ $time ](bold red) '
time_format = "%H:%M â€¢ %d/%m"

[username]
style_user = "bold fg:red"
style_root = "red bold"
format = "[$user â€¢]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "fg:green"
truncation_length = 6
truncation_symbol = "â€¢â€¢/"
format = '(bold fg:red)[$path ]($style)'


[directory.substitutions]
"Desktop" = " ï’© "
"Documents" = " ï’¥ "
"Downloads" = " ï‰ "
"Music" = " ó°ˆ "
"Pictures" = " ï "
"Videos" = " ï”¬ "
"/go" = "/ ó°Ÿ“ "
"/rust" = "/ ó±˜— "
"/gleam" = "/ ï "
"/ts" = "/ îš "

[cmd_duration]
min_time = 0
format = '[î­± $duration](bold fg:cyan) ó±¦™ '
